# Generated by Django 4.2.8 on 2024-01-12 18:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0005_feedback'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='inventory',
            name='quantity_allocated',
        ),
        migrations.RemoveField(
            model_name='inventory',
            name='quantity_in_stock',
        ),
        migrations.AddField(
            model_name='inventory',
            name='is_in_stock',
            field=models.BooleanField(default=True),
        ),
    ]
