# Generated by Django 4.2.8 on 2024-01-12 19:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0007_rename_is_in_stock_inventory_is_available'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='inventory',
            name='is_available',
        ),
        migrations.AddField(
            model_name='inventory',
            name='quantity_allocated',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='inventory',
            name='quantity_in_stock',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
